[tools]
"go:github.com/coreos/butane/internal" = "v0.20.0"
kustomize = "5.4.1"
k0sctl = "0.17.7"
"cargo:coreos-installer" = "latest"
pre-commit = "latest"
kubectl = "latest"

[env]
CONTAINER_ENGINE="docker"
BUTANE_FILES_DIR=""
K0SCTL_USERNAME="admin"
K0SCTL_IDENTITY_PATH="{{ [config_root, '.ssh', 'id_rsa'] | join_path }}"
K0SCTL_BASE_CONFIG_PATH="{{ [config_root, 'config', 'base', 'k0s.Cluster.yaml'] | join_path }}"
K0SCTL_CONFIG_OUTPUT="{{ [config_root, '.cache', 'k0sctl', 'config.yaml'] | join_path }}"
K0SCTL_KUBECONFIG="{{ [config_root, '.cache', '.kube', 'config'] | join_path }}"
K0SCTL_HOSTS=""
K0S_BUTANE_PATH="{{ [config_root, 'config', 'ignition', 'k0s.bu'] | join_path }}"
K0S_IGNITION_PATH="{{ [config_root, '.cache', 'ignition', 'k0s.ign'] | join_path }}"
COREOS_DEST_DEV="/dev/sda"
COREOS_ISO_PATH=""
COREOS_ISO_OUTPUT="out.iso"
KUBECONFIG="{{ env.K0SCTL_KUBECONFIG }}"

[tasks."k0s:apply"]
run = "k0sctl apply -c ${K0SCTL_CONFIG_OUTPUT}"
depends = ["generate:baremetal"]

[tasks."k0s:reset"]
run = "k0sctl reset --force -c ${K0SCTL_CONFIG_OUTPUT}"
depends = ["generate:baremetal"]

[tasks."k0s:config"]
run = """
    #! /usr/bin/env bash
    mkdir -p $(dirname ${K0SCTL_KUBECONFIG})
    k0sctl kubeconfig -c ${K0SCTL_CONFIG_OUTPUT} > ${K0SCTL_KUBECONFIG}
    """

[tasks."flux:apply"]
run = "kubectl apply -k flux"

[tasks."generate:baremetal"]
run = """
    #! /usr/bin/env bash
    mkdir -p $(dirname ${K0SCTL_CONFIG_OUTPUT})
    kustomize build config/overlays/baremetal > ${K0SCTL_CONFIG_OUTPUT}
    """
depends = ["generate:k0s"]

[tasks."generate:k0s"]
run = """
    k0sctl init --k0s \
        --user ${K0SCTL_USERNAME} \
        -i ${K0SCTL_IDENTITY_PATH} \
        ${K0SCTL_HOSTS} > ${K0SCTL_BASE_CONFIG_PATH}
    """

[tasks."generate:iso"]
run = """
    coreos-installer iso customize \
        --dest-device ${COREOS_DEST_DEV} \
        --dest-ignition ${K0S_IGNITION_PATH} \
        --dest-console ttyS0,115200n8 \
        --dest-console tty0 \
        -o ${COREOS_ISO_OUTPUT} ${COREOS_ISO_PATH}
    """
depends = ["generate:ignition"]

[tasks."generate:ignition"]
run = """
    #! /usr/bin/env bash
    mkdir -p $(dirname ${K0S_IGNITION_PATH})
    internal \
    --pretty --strict \
    --files-dir ${BUTANE_FILES_DIR} \
    < ${K0S_BUTANE_PATH} \
    > ${K0S_IGNITION_PATH}
    """
