[tools]
kustomize = "5.4.1"
k0sctl = "0.17.7"
pre-commit = "latest"
kubectl = "latest"

[env]
# Directories
CACHE_DIR="{{ [config_root, '.cache'] | join_path }}"
PKI_DIR="{{ [env.CACHE_DIR, 'pki'] | join_path }}"

# K0SCTL
K0SCTL_USERNAME="admin"
K0SCTL_IDENTITY_PATH="{{ [config_root, '.ssh', 'id_rsa'] | join_path }}"
K0SCTL_BASE_CONFIG_PATH="{{ [config_root, 'k0s', 'k0s.Cluster.yaml'] | join_path }}"
K0SCTL_CONFIG_OUTPUT="{{ [env.CACHE_DIR, 'k0sctl', 'config.yaml'] | join_path }}"
K0SCTL_KUBECONFIG="{{ [env.CACHE_DIR, '.kube', 'config'] | join_path }}"
KUBECONFIG="{{ env.K0SCTL_KUBECONFIG }}"
K0SCTL_HOSTS=""
K0SCTL_CLUSTER_NAME="services"

[tasks."k0s:trust-ca"]
run = """
    #! /usr/bin/env bash
    mkdir -p ${PKI_DIR}

    kubectl get secret ca-root -n cert-manager -o jsonpath='{ .data.ca\\.crt }' | base64 -d > "${PKI_DIR}/k0s-root-ca.pem"
    sudo cp "${PKI_DIR}/k0s-root-ca.pem" /usr/share/pki/ca-trust-source/anchors
    sudo update-ca-trust
"""

[tasks."k0s:apply"]
run = "k0sctl apply -c ${K0SCTL_CONFIG_OUTPUT}"
depends = ["generate:config"]

[tasks."k0s:reset"]
run = "k0sctl reset --force -c ${K0SCTL_CONFIG_OUTPUT}"
depends = ["generate:config"]

[tasks."k0s:config"]
run = """
    #! /usr/bin/env bash
    mkdir -p $(dirname ${K0SCTL_KUBECONFIG})
    k0sctl kubeconfig -c ${K0SCTL_CONFIG_OUTPUT} > ${K0SCTL_KUBECONFIG}
    """
depends = ["generate:config"]

[tasks."flux:apply"]
run = "kubectl apply -k flux"

[tasks."generate:config"]
run = """
    #! /usr/bin/env bash
    mkdir -p $(dirname ${K0SCTL_CONFIG_OUTPUT})
    kustomize build k0s > ${K0SCTL_CONFIG_OUTPUT}
    """
depends = ["generate:k0s"]

[tasks."generate:k0s"]
run = """
    k0sctl init --k0s \
        --user ${K0SCTL_USERNAME} \
        -i ${K0SCTL_IDENTITY_PATH} \
        --cluster-name "${K0SCTL_CLUSTER_NAME}" \
        ${K0SCTL_HOSTS} > ${K0SCTL_BASE_CONFIG_PATH}
    """
