apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: services
spec:
  k0s:
    config:
      spec:
        api:
          address: 10.0.0.200
          externalAddress: homelab.ajphome.com
          sans:
          - 10.0.0.200
        extensions:
          helm:
            repositories:
            - name: fluxcd-community
              url: https://fluxcd-community.github.io/helm-charts
            charts:
            - name: flux2
              chartname: fluxcd-community/flux2
              version: "2.12.4"
              namespace: flux-system
