apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: services
spec:
  k0s:
    config:
      spec:
        extensions:
          helm:
            repositories:
            - name: openebs-internal
              url: https://openebs.github.io/charts
            - name: metallb
              url: https://metallb.github.io/metallb
            - name: jetstack
              url: https://charts.jetstack.io
            - name: nfd
              url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
            - name: intel
              url: https://intel.github.io/helm-charts/
            - name: traefik
              url: https://traefik.github.io/charts
            - name: fluxcd-community
              url: https://fluxcd-community.github.io/helm-charts
            - name: prometheus-community
              url: https://prometheus-community.github.io/helm-charts
            charts:
            - name: openebs
              chartname: openebs-internal/openebs
              version: "3.9.0"
              namespace: openebs-system
              order: 1
              values: |
                localprovisioner:
                  hostpathClass:
                    enabled: true
                    isDefaultClass: true
            - name: flux2
              chartname: fluxcd-community/flux2
              order: 2
              version: "2.12.4"
              namespace: flux-system
            - name: metallb
              chartname: metallb/metallb
              namespace: metallb-system
              order: 3
            - name: traefik
              chartname: traefik/traefik
              order: 4
              version: "20.5.3"
              namespace: traefik-system
            - name: cert-manager
              chartname: jetstack/cert-manager
              order: 5
              namespace: cert-manager
              version: "v1.14.2"
              values: |
                installCRDs: true
            - name: nfd
              chartname: nfd/node-feature-discovery
              order: 6
              namespace: node-feature-discovery
              version: "0.15.1"
            - name: dp-operator
              chartname: intel/intel-device-plugins-operator
              order: 7
              namespace: inteldeviceplugins-system
            - name: gpu
              chartname: intel/intel-device-plugins-gpu
              order: 8
              namespace: inteldeviceplugins-system
              values: |
                nodeFeatureRule: true
            - name: kube-prometheus-stack
              chartname: prometheus-community/kube-prometheus-stack
              order: 9
              namespace: monitoring
              values: |
                alertmanager:
                  enabled: false
                grafana:
                  persistence:
                    enabled: true
                    type: sts
                    storageClassName: "openebs-hostpath"
                    accessModes:
                    - ReadWriteOnce
                    size: 20Gi
                    finalizers:
                    - kubernetes.io/pvc-protection
                prometheus:
                  prometheusSpec:
                    storageSpec:
                      volumeClaimTemplate:
                        spec:
                          storageClassName: "openebs-hostpath"
                          accessModes:
                          - ReadWriteOnce
                          resources:
                            requests:
                              storage: 50Gi
                        selector: {}
