apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  annotations:
    dns.alpha.kubernetes.io/ingress-hostname-source: defined-hosts-only
spec:
  tls:
  - hosts:
    - grafana.ajphome.com
    secretName: grafana-tls
  rules:
  - host: grafana.ajphome.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: monitoring-kube-prometheus-stack-grafana
            port:
              number: 80
