apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls
spec:
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
      - AJP
  commonName: prometheus.ajphome.com
  isCA: false
  dnsNames:
  - prometheus.ajphome.com
  secretName: prometheus-tls
  issuerRef:
    name: ca
    kind: ClusterIssuer
