apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls
spec:
  dnsNames:
  - prometheus.ajphome.com
  secretName: prometheus-tls
  issuerRef:
    name: ca
    kind: ClusterIssuer
