apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  annotations:
    external-dns.alpha.kubernetes.io/hostname: prometheus.ajphome.com.
spec:
  tls:
  - hosts:
    - prometheus.ajphome.com.
    secretName: prometheus-tls
  rules:
  - host: prometheus.ajphome.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-prometheus-stack-prometheus
            port:
              number: 9090
