apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
  template:
    spec:
      containers:
      - name: web
        image: web
        volumeMounts:
        - name: data
          mountPath: /opt/meshcentral/meshcentral-data
        - name: config
          mountPath: /opt/meshcentral/meshcentral-data/config.json
          subPath: config.json
        resources:
          limits:
            memory: "256Mi"
            cpu: "1000m"
        ports:
        - name: https
          containerPort: 443
        - name: bio
          containerPort: 4433
      volumes:
      - name: config
        configMap:
          name: meshcentral-web
      - name: data
        persistentVolumeClaim:
          claimName: web
