apiVersion: v1
kind: Service
metadata:
  name: web
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.0.0.201
spec:
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: https
  - name: bio
    port: 4433
    targetPort: bio
