apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  selector:
  template:
    spec:
      containers:
      - name: server
        image: server
        env:
        - name: TFTPD_OPTS
          value: -R 64000:64000
        volumeMounts:
        - name: config
          mountPath: /config
        - name: assets
          mountPath: /assets
        - name: server
          mountPath: /etc/sysctl.conf
          subPath: sysctl.conf
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - name: tftp
          containerPort: 69
          protocol: UDP
        - name: ephemeral
          containerPort: 64000
          protocol: UDP
        - name: assets
          containerPort: 80
        - name: web
          containerPort: 3000
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config
      - name: assets
        persistentVolumeClaim:
          claimName: assets
      - name: server
        configMap:
        - name: server
