apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: server
  newName: ghcr.io/netbootxyz/netbootxyz
  newTag: latest
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: server
resources:
- deployment.yaml
- service.yaml
- assets.pvc.yaml
- config.pvc.yaml
