apiVersion: v1
kind: Service
metadata:
  name: server-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "server"
spec:
  type: LoadBalancer
  ports:
  - name: tftp
    port: 69
    targetPort: tftp
    protocol: UDP
