apiVersion: v1
kind: Service
metadata:
  name: server-udp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: tftp
    port: 69
    targetPort: tftp
    protocol: UDP
  - name: ephemeral
    port: 64000
    targetPort: ephemeral
    protocol: UDP
