apiVersion: v1
kind: Service
metadata:
  name: server-udp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: tftp
    port: 69
    targetPort: tftp
    protocol: UDP
  - name: tid-start
    port: 64001
    targetPort: tid-start
    protocol: UDP
  - name: tid-end
    port: 64002
    targetPort: tid-end
    protocol: UDP
