apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
spec:
  targetNamespace: intel-device-plugins-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: intel-device-plugins-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: intel
  interval: 10m0s
