apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- homelab.gitrepository.yaml
- metallb.kustomization.yaml
- monitoring.kustomization.yaml
- cert-manager.kustomization.yaml
- openebs.helmrepository.yaml
- openebs.helmrelease.yaml
- metallb.helmrepository.yaml
- metallb.helmrelease.yaml
- jetstack.helmrepository.yaml
- cert-manager.helmrelease.yaml
- nfd.helmrepository.yaml
- node-feature-discovery.helmrelease.yaml
- intel.helmrepository.yaml
- intel-device-plugins-operator.helmrelease.yaml
- intel-device-plugins-gpu.helmrelease.yaml
- traefik.helmrepository.yaml
- traefik.helmrelease.yaml
- prometheus-community.helmrepository.yaml
- kube-prometheus-stack.helmrelease.yaml
- bitnami.helmrepository.yaml
- external-dns.helmrelease.yaml
