apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
spec:
  interval: 5m0s
  path: ./monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
  targetNamespace: monitoring
