apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: netbootxyz
spec:
  interval: 5m0s
  path: ./netbootxyz/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
