apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: spin-operator
spec:
  targetNamespace: spin-operator
  install:
    createNamespace: true
  chart:
    spec:
      chart: spin-operator
      version: 0.2.*
      sourceRef:
        kind: HelmRepository
        name: spinkube
  interval: 10m0s
